[package]
edition = "2021"
name = "velvet_rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dasp = "0.11.0"
easyfft = "0.4.0"
hound = "3.5.0"
rand = "0.8.5"
rayon = "1.8.0"
timeit = "0.1.2"
